
        /*
                *  AUTO-GENERATED FILE.  DO NOT MODIFY. 
                *  
                *  This class was automatically generated by the 
                *  aapt tool from the resource data it found.  It  should not be modified by hand.  
        */
        
        /* Generated Code Do Not Modify */
        




















        //Current folder imports from return types, extended types, and scope (deduplicated)
        
export class R
            extends Object
         {
        

export class attr
            extends Object
         {
        
/*Static stuff is not allowed for Typescript inner classes*//**/


}
                
            
export class drawable
            extends Object
         {
        
/*Static stuff is not allowed for Typescript inner classes*/
    public static readonly testgamedemo_icon: number = 0x7f020000;
        
        

    public static readonly testgamedemo_wait_256_by_256: number = 0x7f020001;
        
        
/**/


}
                
            
export class id
            extends Object
         {
        
/*Static stuff is not allowed for Typescript inner classes*/
    public static readonly ad_area_bottom: number = 0x7f060002;
        
        

    public static readonly ad_area_left: number = 0x7f060003;
        
        

    public static readonly ad_area_right: number = 0x7f060004;
        
        

    public static readonly ad_area_top: number = 0x7f060001;
        
        

    public static readonly testgamedemo: number = 0x7f060000;
        
        

    public static readonly testgamedemo_gl: number = 0x7f060005;
        
        
/**/


}
                
            
export class layout
            extends Object
         {
        
/*Static stuff is not allowed for Typescript inner classes*/
    public static readonly testgamedemo_ad_overlay_layout: number = 0x7f030000;
        
        

    public static readonly testgamedemo_gl_layout: number = 0x7f030001;
        
        

    public static readonly testgamedemo_layout: number = 0x7f030002;
        
        
/**/


}
                
            
export class raw
            extends Object
         {
        
/*Static stuff is not allowed for Typescript inner classes*/
    public static readonly error: number = 0x7f040000;
        
        

    public static readonly licenseinitdata: number = 0x7f040001;
        
        

    public static readonly partner: number = 0x7f040002;
        
        

    public static readonly select: number = 0x7f040003;
        
        

    public static readonly test: number = 0x7f040004;
        
        

    public static readonly testgamedemo_wait_256_by_256: number = 0x7f040005;
        
        

    public static readonly ouya_a: number = 0x7f040012;
        
        

    public static readonly ouya_key: number = 0x7f040013;
        
        

    public static readonly ouya_o: number = 0x7f040014;
        
        

    public static readonly ouya_u: number = 0x7f040015;
        
        

    public static readonly ouya_y: number = 0x7f040016;
        
        

    public static readonly touch_button_128_by_128: number = 0x7f040026;
        
        

    public static readonly touch_button_64_by_64: number = 0x7f040027;
        
        

    public static readonly touch_button_create_128_by_128: number = 0x7f040028;
        
        

    public static readonly touch_button_create_64_by_64: number = 0x7f040029;
        
        

    public static readonly touch_button_down_arrow_128_by_128: number = 0x7f04002a;
        
        

    public static readonly touch_button_down_arrow_64_by_64: number = 0x7f04002b;
        
        

    public static readonly touch_button_generic_action_128_by_128: number = 0x7f04002c;
        
        

    public static readonly touch_button_generic_action_64_by_64: number = 0x7f04002d;
        
        

    public static readonly touch_button_join_128_by_128: number = 0x7f04002e;
        
        

    public static readonly touch_button_join_64_by_64: number = 0x7f04002f;
        
        

    public static readonly touch_button_leave_128_by_128: number = 0x7f040030;
        
        

    public static readonly touch_button_leave_64_by_64: number = 0x7f040031;
        
        

    public static readonly touch_button_login_128_by_128: number = 0x7f040032;
        
        

    public static readonly touch_button_login_64_by_64: number = 0x7f040033;
        
        

    public static readonly touch_button_next_128_by_128: number = 0x7f040034;
        
        

    public static readonly touch_button_next_64_by_64: number = 0x7f040035;
        
        

    public static readonly touch_button_refresh_128_by_128: number = 0x7f040036;
        
        

    public static readonly touch_button_refresh_64_by_64: number = 0x7f040037;
        
        

    public static readonly touch_button_start_128_by_128: number = 0x7f040038;
        
        

    public static readonly touch_button_start_64_by_64: number = 0x7f040039;
        
        

    public static readonly touch_button_add_local_player_128_by_128: number = 0x7f040038;
        
        

    public static readonly touch_button_add_local_player_64_by_64: number = 0x7f040039;
        
        

    public static readonly touch_button_strafe_left_arrow_128_by_128: number = 0x7f04003a;
        
        

    public static readonly touch_button_strafe_left_arrow_64_by_64: number = 0x7f04003b;
        
        

    public static readonly touch_button_strafe_right_arrow_128_by_128: number = 0x7f04003c;
        
        

    public static readonly touch_button_strafe_right_arrow_64_by_64: number = 0x7f04003d;
        
        

    public static readonly touch_button_turn_left_arrow_128_by_128: number = 0x7f04003e;
        
        

    public static readonly touch_button_turn_left_arrow_64_by_64: number = 0x7f04003f;
        
        

    public static readonly touch_button_turn_right_arrow_128_by_128: number = 0x7f040040;
        
        

    public static readonly touch_button_turn_right_arrow_64_by_64: number = 0x7f040041;
        
        

    public static readonly touch_button_up_arrow_128_by_128: number = 0x7f040042;
        
        

    public static readonly touch_button_up_arrow_64_by_64: number = 0x7f040043;
        
        

    public static readonly touch_button_generic_action_arrow_64_by_64: number = 0x7f040009;
        
        
/**/


}
                
            
export class string
            extends Object
         {
        
/*Static stuff is not allowed for Typescript inner classes*/
    public static readonly progressbar_in_title_string: number = 0x7f050001;
        
        

    public static readonly testgamedemo_app_name: number = 0x7f050000;
        
        
/**/


}
                
            
}
                
            

